<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tutup Poster_gambar</name>
   <tag></tag>
   <elementGuidId>e5523cab-0945-487f-928e-c38b44d3ff88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kuesioner_modal']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.gambar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>742044dd-6679-44c0-8572-f8a0b0224b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gambar</value>
      <webElementGuid>8c88dc05-a428-475f-9d4e-b76dc80801c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://peo.pelindo.id/images/flyer/06b79bcd-0cb1-4a10-b4e5-97f8bd4e32a4.jpeg</value>
      <webElementGuid>87785090-d001-4a06-b05e-9d9f201be028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kuesioner_modal&quot;)/div[@class=&quot;mySlides&quot;]/img[@class=&quot;gambar&quot;]</value>
      <webElementGuid>dc82cce4-f00a-4f16-8517-5c983c233e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kuesioner_modal']/div/img</value>
      <webElementGuid>2c50ec7d-0f1e-4a4f-8653-0901a3c2964b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://peo.pelindo.id/images/flyer/06b79bcd-0cb1-4a10-b4e5-97f8bd4e32a4.jpeg')]</value>
      <webElementGuid>69b0ba7f-2898-42a6-a00c-f1dfb46b1d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/img</value>
      <webElementGuid>265a5b09-f1d1-421e-b36d-d8408933f4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://peo.pelindo.id/images/flyer/06b79bcd-0cb1-4a10-b4e5-97f8bd4e32a4.jpeg']</value>
      <webElementGuid>78bf5c0b-c916-4339-9e53-35ba60ea272a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
